---
version: 2 # use CircleCI 2.0
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.12 #
    steps:
      - checkout # Descargar el codigo de github
      - add_ssh_keys:
          fingerprints:
            - "79:c4:eb:9d:c6:69:32:97:99:31:3c:bf:b4:da:65:2b"      
      - run:
          name: Probar ssh
          command: ssh pauler@ivantrips.com ls            
      - run:
          name: Imprimir mensaje de pauler
          command: echo "We are amazing"
      - run:
          name: Compilar el codigo
          command: GOOS=linux GOARCH=amd64 go build -o emailapp main.go
      - run:
          name: Comprobar
          command: ls

                  
